<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Albendazole</name>
   <tag></tag>
   <elementGuidId>344da872-cb88-49e1-99ea-f9581b35e04c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;optmedicine&quot;)[count(. | //select[@id = 'optmedicine']) = count(//select[@id = 'optmedicine'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optmedicine</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Albendazole  (single dose)-400 mgAmlodepin -5 mgAmoxycilin- 250 mg, Cloxacilin-250 mgAmoxycillin -250 mgAmoxycillin - 250 mg, Clavulanic Acid 125 mg Amoxycillin - 500 mg -500 mgAmoxycillin - 500mg, Clavulanic Acid 125 mgAmoxycillin(Dispersable)-125  mgAmoxycilline - 875 mg, Clavulanic Acid 125 mgAntacid (dried Alum, Hydrox gel - 240mg. Mag Hydrox - 100mg, carb - 60 mg, activated dimethicome - 25 mg)Atenolol-50 mgAzithromycin-250 mgBisacodyl-5 mgCefixime -200 mgCetrizine -10 mgChloroquin -150 mgChlorpheniramine maleate -4 mgCiprofloxacin-500 mgClarithromycin-500 mgClopidogrel-75 mgClotrimazole Vag with Applicator-100 mgCycloserine -250 mgDexamethasone-0.5 mgDibasic calcium phospate dihydrate 500 mg. vitamin D3 200 iuDiclofenac 50 mg with paracetamol - 500 mgDicyclomin HCL -20 mgDomperidone -10 mgDoxycylone -100 mgErythomycin salt -500 mgEthambutol -800 mgEthambutol -200 mgEthambutol -400 mgEthionamide -250 mgEtophylline - 77 mg. Theophylline - 23 mgFerrous Ascorbate 100 mg, Folic Acid 1.5 mgFlucanzole single dose-150 mgFolic Acid-5 mgFolic Acide 0.1 mg, Ferrous Sulphate 67 mg (small)Furazelidone-100 mgGibenciamide -5 mgGlimipride-1 mgGriseofulvin -125 mgIbuprofen 400mg+Pracetamol 325mg-5 mgIsoniazid -100 mgIsoniazid -300 mglbuprolen 400 mg + Paracetamol 325 mg--Levocetrizine hcl -5 mgLevofloxacin -250 mgLevofloxacin -500 mgLinezolid-600 mgMebendazole -100 mgMeiformin HCL -500 mgMoxifloxacin-400 mgMultivitamin (Vitamin B1+B2+b6+B12+NiacinamideOmeprazole -20 mgOndensetron-8 mgParacetamol-500 mgPhenytonin Sodium-100 mgPhyrizinamide -500 mgPrednisolone-5 mgPrimaquine -2.5 mgprimaquine -7.5 mgPyrizinamide -750 mgRamipril -2.5 mgRanitidine-150 mgRifampicin-150 mgRifampicin -450 mgSalbutamol-4 mgtestmed-350mgTetracycline HCL -250 mgTrypsin and chymotrypsin 100000 A.V.Vit B Complex</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optmedicine&quot;)</value>
   </webElementProperties>
</WebElementEntity>
