<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Adernaline 0.</name>
   <tag></tag>
   <elementGuidId>de5a05f8-84d0-46c0-b086-71c3f6f08beb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optmedicine</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Adernaline 0.1% Aqueous -1mgAmikacin -500 mgAmikacin -100 mgAminophylline -25 mgAmoxycillin 1000mg. Clavulanic Acid 200mg - AdultAmoxycillin 1000mg. Clavulanic Acid 50mg - PaedatricAnti Snake VenomAnti-Rabies VaccineArtesunate 60mg with sodium bicarbonate 5% 1ml, sodium chloride 0.9% 5ml-60 mgAtopine Sulphate -0.6 mgBupivacaine HCL Heavy-20 mgCalcium Gluconate 10%Caprecomycin-750 mgCaprecomycin-1000 mgCarboprost tromethamine -250 mgCefoperazone 1000mg with sulbactam 500 mgCefotaxaime -1 gmCeftrioxone-1 gmCiprofloxacin-200 mgCiprofloxacin-200 mgDexamethasone phosphate-4 mgDextrose Anhydrous 25% 100 ml.Diclofenac Sodium -25 mgDicyclomin -20 mgDopmine Hydrochloride-200 mgDrotaverine -40 mgEtophylline and Theophylline -220 mgFrusemide -10 mgHydrocortisone sodium succinate-100 mgIron Suorose-20 mgKanamycin -500 mgKanamycin -1000 mgMannitol-20 gMephentaramine Sulphate-30 mgMethyl Ergometrine -0.2 mgMetronidazole IV -5 mgMidazolam -1 mgMultivitamin Ondensetron-2 mgOxytocin -8.5 micro gramPaediatric maintenance solution with 5% Dextrose-500 mlPAM (Pralidoxime Chloride)-500 mgPantoprazole -40 mgParacetamol I V-10 mgPentazocine Lactate 30mg/ml.-30 mgPheniramine Maleate -22.75 mgPhenytoin Sodium-50  mgPiperacillin 4000 mg., Tazobactam 500 mgProductTEST-500Promethazine Hydrochloride 2.5%-2 mgPropofol -10 mgRanitidine -25 mgRinger Lactate IVSalbutamol-500sodium Bicarbonate 7.5%-3.75 mgSodium Chloride 0.9% (Non returnable glass bots of non toxic plastic containers)-500 mlSodium Chloride 0.9% (Non returnable glass bots of non toxic plastic containers)-100 mlStreptomycin-750 mgTESTsome-100Tramadol Hydrochloride -100 mgValethamate Bromide -8 mgVit. K1 10mg-10 mgWater for injection I.P.-5 ml</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optmedicine&quot;)</value>
   </webElementProperties>
</WebElementEntity>
