<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Schedule 1Inj</name>
   <tag></tag>
   <elementGuidId>85dbc2c9-67f3-4cc6-bd2d-4713a9de877a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;optcategory&quot;)[count(. | //select[@id = 'optcategory']) = count(//select[@id = 'optcategory'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optcategory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Schedule 1/InjectionSchedule 3/Syrup ,drops,OintmentsSchedule 5/Drug and ChemicalSchedule 7/Surgical dressing ,Suturing materialSchedule 8/Needles and SyringesSchedule 9/Surgical Rubbers goods Schedule 12/Linen Material</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optcategory&quot;)</value>
   </webElementProperties>
</WebElementEntity>
