<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Advance E.C.G</name>
   <tag></tag>
   <elementGuidId>07d88acb-283e-49e0-87ab-6ce7ebf0360d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optmedicine</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Advance E.C.G. Machine with auto reportingAir Cannyka 26 Gauge Apex Locator Root ZX-IIArtery ForcepAscan biometerB.P. Handle No. 03Ball point cauteryBall Point ProbC Arm Machine hi frequency for Orthopedic Dept.Chisel 2 mmChisel 3 mmChisel 4 mmCocodile Fine ForcepConjunctival ScissorsCorneal ScissorsCrocodile Punch Actron JawDepth GaugeDiamond Burs (Cavity Cutting) SetDoyen Mouth Gag AdultE.S.R. AnalyserEar periosteum ElevatorEar SpecullumElectrolyte Analyser with U.P.S.Extraction Forcep sets (Pedo)Fine CurretteFixation forcepsFreer Elevator with Angle edgeFreer Elevator with round edgeFully Automatic Autoanalyser with U.P.S. for Biochemistry test - 360 test per hourGlucometer for lab useGouge 2 mmGouge 3 mmGrauvlahon ForcepHeine fibre optic otoscopeIrris Repositor Lampert-50Limps ForcepsMalieus NipplerMastoid Retractor 2 toothMastoid Retractor 3 toothMastoid Retractor 4 toothMC Pherson lens forcepsMetal cutterMicro Needle HolderMobie X-Ray machine with Hi-frequence - 100 M.A.Mouth Gag Child DoyenMouth gag jenning child Mouth gag jenning child Multiparamonitor - 5 parametersMuscle hookN.S.T. Machine for Gynaec dept. useNibblerOxygen flow meterPartical cell counter - 3 parts Pick 0.5 mmPiston Holding ForcepsRight Angle Round KnifeSick Knife up cuttingSickle Knife DowncuttingSide KnifeSimcoe Cannula No. 22Single SpecullumSinskey DiallerSmall ScissorStainless Box with matStapedectomy fine instrument setSuction Tips (Sillicon)Suction TubeSuperior rectus Forceps Superior rectus needle HolderSurgical Scissor Suture Tying forcepsTunning fork 256 HzTunnning fork 1024 HzTunnning fork 512 HzV.D.R.L. RotatorVannas Scissors Wash Cannula 20 GuageWire Vectils</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optmedicine&quot;)</value>
   </webElementProperties>
</WebElementEntity>
