<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--</name>
   <tag></tag>
   <elementGuidId>a008494f-21ef-45ff-b93d-24e86e307d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;optstatus&quot;)[count(. | //select[@id = 'optstatus' and (text() = '
                                --Select--
                                Approved
                                Declined
                            ' or . = '
                                --Select--
                                Approved
                                Declined
                            ')]) = count(//select[@id = 'optstatus' and (text() = '
                                --Select--
                                Approved
                                Declined
                            ' or . = '
                                --Select--
                                Approved
                                Declined
                            ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optstatus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                --Select--
                                Approved
                                Declined
                            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optstatus&quot;)</value>
   </webElementProperties>
</WebElementEntity>
