<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Schedule 1Inj</name>
   <tag></tag>
   <elementGuidId>2d8a6850-37cc-4a33-92eb-82cecf27db28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;optcategory&quot;)[count(. | //select[@id = 'optcategory']) = count(//select[@id = 'optcategory'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optcategory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Schedule 1/InjectionSchedule 2/Tablet and CapsuleSchedule 3/Syrup ,drops,OintmentsSchedule 4/X-raySchedule 5/Drug and ChemicalSchedule 6/Re agent, Chemical stains and kitsSchedule 7/Surgical dressing ,Suturing materialSchedule 8/Needles and SyringesSchedule 9/Surgical Rubbers goods Schedule 10/Laboratory Articles and Surgical Sundries'Schedule 11/Medical Equipments and InstrumentsSchedule 12/Linen MaterialSchedule 13/KITCHENITEMSSchedule 14/EQUIPMENTS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optcategory&quot;)</value>
   </webElementProperties>
</WebElementEntity>
