<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Albumin kit (</name>
   <tag></tag>
   <elementGuidId>9f1a3538-7739-4a86-a0e4-0b13e58297ca</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optmedicine</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Albumin kit (Auto)Bilirubin Kit (Auto)Cholesterol Kit (Auto) with StandardCreatinine kit (Auto) with standardGod Pod Kits (Auto) Glocose Kit auto with standardR.A. Antigen Kit slide methodS.G.O.T. Kits (Auto)S.G.P.T. Kits (Auto)Sr. Calcium kit Aresenazo (Auto)Total Protein (Auto) KitTriglyceride Kit (Auto)Urea kit TC (Auto)Uric Acid kit (Auto)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optmedicine&quot;)</value>
   </webElementProperties>
</WebElementEntity>
