<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--ALL--</name>
   <tag></tag>
   <elementGuidId>5f072ab7-65c5-40f7-a4fb-8e84aaefcd47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;optdept&quot;)[count(. | //select[@id = 'optdept' and (text() = '
                --ALL--
                Inpatient
                Pharmacy
                Kitchen
                Lab
                HealthPost
                Dispensary
                Emergency
            ' or . = '
                --ALL--
                Inpatient
                Pharmacy
                Kitchen
                Lab
                HealthPost
                Dispensary
                Emergency
            ')]) = count(//select[@id = 'optdept' and (text() = '
                --ALL--
                Inpatient
                Pharmacy
                Kitchen
                Lab
                HealthPost
                Dispensary
                Emergency
            ' or . = '
                --ALL--
                Inpatient
                Pharmacy
                Kitchen
                Lab
                HealthPost
                Dispensary
                Emergency
            ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optdept</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                --ALL--
                Inpatient
                Pharmacy
                Kitchen
                Lab
                HealthPost
                Dispensary
                Emergency
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optdept&quot;)</value>
   </webElementProperties>
</WebElementEntity>
