<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Baby sheet (R</name>
   <tag></tag>
   <elementGuidId>9a8dd3cc-fe66-4950-a59d-c6cdad89640b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optmedicine</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Baby sheet (Rapper) Size 45 inchesx45 inchesBlanket size 54 inchesx90 inchesColour bed sheet (palin size 24 inchesx90 inches)Colour Pillow cover size 16:x22 inchesColour Towel (Cotton) Small SizeCotton Pillow (1.5 lg) size 16 inchesx22 inchesCurtain Cloth Green 36 inches PannaDraw sheet (Rapper) Size 45 inchesx45 inchesOperation Hole towel size - 38 inchesx46 inches 8 inches Hole at centre 1 and Half lengthOperation Mask (Green)Operation Towel Size - 38 inchesx46 inchesPatient Payjama (Ladies) Female Gaown sky blue colour long 42 inchesready.Surgeon Operation Gaown Standard Size Turkish Towel a) White Big size - 27 inchesx54 inchesTurkish Towel a) White small size - 12 inchesx18 inchesTurkish Towel a) White small size - 12 inchesx18 inchesWhite bed sheet (plain size 54 inchesx90 inches)White Pillow cover size -  16:x22 inchesWhite Pillow Cover size - 16 inchesx22 inches</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optmedicine&quot;)</value>
   </webElementProperties>
</WebElementEntity>
